export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_RECEIVE = 'FETCH_MOVIES_RECEIVE';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';

export const FETCH_CURRENT_MOVIE_RECEIVE = 'FETCH_CURRENT_MOVIE_RECEIVE';

export const GET_SIMILAR_MOVIES = 'GET_SIMILAR_MOVIES';
export const FETCH_SIMILAR_MOVIES_REQUEST = 'FETCH_SIMILAR_MOVIES_REQUEST';
export const FETCH_SIMILAR_MOVIES_RECEIVE = 'FETCH_SIMILAR_MOVIES_RECEIVE';
export const FETCH_SIMILAR_MOVIES_FAILURE = 'FETCH_SIMILAR_MOVIES_FAILURE';

export const CHANGE_TYPE_OF_SEARCH = 'CHANGE_TYPE_OF_SEARCH';
export const CHANGE_TYPE_OF_SORT = 'CHANGE_TYPE_OF_SORT';
